import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navigation/NavBar";

import LenisScroller from "@/components/LenisScroller";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar></NavBar>
        <main>{children}</main>
        <LenisScroller />
      </body>
    </html>
  );
}
